Tidy up - WIP
dwyl/tachyons-bootstrap pull request #50
Opened 2017-06-16 13:39 UTC by Cleop

Tackles issues from #43 broken into separate issues:
- #44 Creates a table of contents linking to each section
- #45 Adds dwyl colours for grid section
- #46  Thins and makes colors of input borders consistent
- #47 Ensures titles read 'Tachyons Bootstrap'
- #48 Adds github star count badge

2017-06-16 17:49 UTC, nelsonic approved these changes
@Cleop Looks (_really_) Good! 🎉 
(_thanks for making time to do this_)

2017-06-17 18:35 UTC, iteles commented
Odd. Tried to run this branch and localhost just hangs.

Will try again tomorrow after I try to shut down my computer overnight. Might  be a local thing.

2017-06-18 18:52 UTC, iteles reviewed
@cleop This is still hanging for me. Do you have 5 mins to review with me tomorrow please? 😊

2017-06-18 20:41 UTC, katbow commented on index.html
> +    <link rel="stylesheet" href="style.css">
You'll need to serve this file as well. Right now it only serves the index & each of the components. Not set up to serve `.css` files yet 👍

2017-06-18 20:42 UTC, katbow requested changes
Looks good @Cleop! Just need to address the css file & should work a charm 👌 ✨

2017-06-20 10:15 UTC, Cleop commented
Changes now made. Please now review @iteles and let me know if you encounter any more problems!

2017-06-20 10:25 UTC, katbow commented
Can a [test](https://github.com/dwyl/tachyons-bootstrap/blob/master/test/test.js) be added for the additions to `component_combiner.js`? That should keep it at 100% 🙂 💃

2017-06-20 11:01 UTC, Cleop commented
Opps! Sorry for missing that. Here we go! @katbow

2017-06-20 12:49 UTC, katbow approved these changes
Great work @Cleop ! Thanks for updating 🎉

2017-06-20 12:49 UTC, katbow commented on component_combiner.js
> +  } else if (req.url === '/style.css') {
👍

2017-06-20 12:49 UTC, merged